version: '3.9'

services:
  #php    ./app
  app:
    build: ./
    container_name: web-app
    context:
    dockerfile: ./docker/Dockerfile
    depends_on:
      - database
    env_file:
      - .env.local
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html

  database:
    image: mysql:8.0
    container_name: db_app
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
###< doctrine/doctrine-bundle ###
  my_service:
    build:
      context: .
      args:
        - VAR1=value1
        - VAR2=value2
        -
volumes:





