version: '3.9'
services:
  app:
    container_name: web-app
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    image: php:8.1-apache
    depends_on:
      - database
    networks:
      - connect
    ports:
      - "8080:80"
    # "/path/to/volume:/mount/point"
    volumes:
      - ./webapp:/var/www/html
      - ./log:/var/log/apache2/
      - ./vhosts:/etc/apache2/sites-available/

  #mounted in all application
  database:
    image: mysql:8.0
    container_name: db_app
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony-devops
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    networks:
      - connect
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      -
  jenkins:
    image: 'jenkins/jenkins:lts-jdk11'
    container_name: "jenkins"
    labels:
      kompose.service.type: nodeport
    ports:
      - '8080:8080'
      - '443:8443'
      - '50000:50000'
    volumes:
      - /srv/data/jenkins_data:/jenkins_home
      - /srv/data/jenkins:/var/jenkins_config

networks:
  connect:
    driver: bridge
# https://docs.docker.com/storage/
volumes:
  webapp:
    driver: local
  log:
    driver: local
  vhosts:
    driver: local
  db-data:
    driver: local
  jenkins_data:
    driver: local
    external: true
  jenkins:
    driver: local
    external: true