version: '3.9'
services:
  app:
    container_name: web-app
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    image: php:8.1-apache
    depends_on:
      - database
    networks:
      - connect
    # mapper le port conteneur:au port de l'hote client
    #machine local app:conteneur
    ports:
      - "8080:80"

    volumes:
      - ./webapp:/var/www/html
      - ./log:/var/log/apache2/
      - ./vhosts:/etc/apache2/sites-available/

  database:
    container_name: app-database
    image: mysql:8.0
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_app
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    networks:
      - connect
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  jenkins:
    container_name: "jenkins"
    image: 'jenkins/jenkins:lts-jdk11'
    # Kubernetes.ip volumes
    labels:
      #Kuvernetes configuration
      kompose.service.type: nodeport
    networks:
      - api
    ports:
      - '8080:8080'
      - '443:8443'
      - '50000:50000'
    volumes:
      - /srv/data/jenkins_data:/jenkins_home
      - /srv/data/jenkins:/var/jenkins_config

  docker:
    container_name: "docker"
    image: 'docker'
    networks:
      - api
    ports:
      - '4243:32768'
    volumes:
      -  /lib/systemd/system/docker.service:/docker_service


networks:
  connect:
    driver: bridge
  api:
    driver: bridge

#volumes missing
# vhosts / log / webapp  |  ok html-log-vhost mounted ok | manque copy projet
# docker.service  | mount ok / pas encore de data | 1 fichier pour API

volumes:
  webapp:
    driver: local
  log:
    driver: local
  vhosts:
    driver: local
  db-data:
    driver: local
  jenkins_data:
    driver: local
  jenkins:
    driver: local
  docker.service:
    driver: local
