version: '3.9'

services:
  app:
    container_name: web-app
    build:
      context: ./docker/
      dockerfile: ./docker/Dockerfile
    depends_on:
      - database
    networks:
      - appconnect
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html

  database:
    image: mysql:8.0
    container_name: db_app
    env_file:
      - .env.local
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - appconnect
    ports:
    - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  networks:
      appconnect:






