version: '3.9'
services:
  app:
    container_name: web-app
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - database
    networks:
      - connect

    # client ecoute : conteneur envoie
    # [host_port]:[container_port]
    ports:
      - '8090:8088'
    volumes:
      - webapp:/var/www/
      - log:/var/log/apache2/
      - vhosts:/etc/apache2/sites-available/

  database:
    container_name: app-database
    image: mysql:8.0
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_app
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    networks:
      - connect
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  jenkins:
    container_name: "jenkins"
    image: 'jenkins/jenkins:lts-jdk11'
    # Kubernetes.ip volumes
    labels:
      #Kuvernetes configuration
      kompose.service.type: nodeport
    networks:
      - api
    ports:
      - "8080:80"
      - '443:8443'
      - '50000:50000'
    volumes:
      - /srv/data/jenkins_data:/jenkins_home
      - /srv/data/jenkins:/var/jenkins_config

  # Passthrough /lib/modules into the container (-v /lib/modules:/lib/modules)
  docker:
    container_name: "docker"
    build:
      context: ./docker/
      dockerfile: dockerDockerfile1
    privileged: true
    cap_add:
      - 'ALL'
    networks:
      - api
    ports:
      - '4243:32768'
    # copy coller le fichier source ajouter un context?
    volumes:
      -  docker-service:/lib/systemd/system/

networks:
  connect:
    driver: bridge
  api:
    driver: bridge

volumes:

  webapp:
    driver: local
  log:
    driver: local
  vhosts:
    driver: local

  db-data:
    driver: local

  jenkins_data:
    driver: local
  jenkins:
    driver: local

  docker-service:
    driver: local
