version: '3.9'
services:
  app:
    container_name: web-app
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - database
    networks:
      - connect

    # [host_port]:[container_port]
    ports:
      - '8090:80'

    # [hote_path]:[container or path]  inversible
    # ? doit etre relie au projet?
    volumes:
      - webapp:/var/www/
      - log:/var/log/apache2/
      - vhosts:/etc/apache2/sites-available/

  database:
    container_name: app-database
    image: mysql:8.0
    restart: always
    env_file:
      - .env.local
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}

    networks:
      - connect

    ports:
      - "3307:3307"
    volumes:
      - db-data:/var/lib/mysql

  jenkins:
    container_name: "jenkins"
    image: 'jenkins/jenkins:lts-jdk11'
    labels:
      #Kuvernetes configuration
      kompose.service.type: nodeport
    ports:
      - "8080:80"
      - '443:443'
      - '50000:50000'
    volumes:
      - /srv/data/jenkins_data:/jenkins_home
      - /srv/data/jenkins:/var/jenkins_config
      - /var/run/docker.sock:/var/run/docker.sock

# definissent volumes ok
#      - jenkins_data:/jenkins_home
#      - jenkins:/var/jenkins_config

networks:
  connect:
    driver: bridge

volumes:
  webapp:
    driver: local
  log:
    driver: local
  vhosts:
    driver: local


  db-data:
    driver: local

  jenkins_data:
    driver: local
  jenkins:
    driver: local

