version: '3.9'
services:
  app:
    container_name: web-app
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - database
    networks:
      - connect

    # [host_port]:[container_port]
    ports:
      - '8080:80'

    volumes:
      - webapp:/var/www/
      - log:/var/log/apache2/
      - vhosts:/etc/apache2/sites-available/

  database:
    container_name: app-database
    image: mysql:8.0
    restart: always
    env_file:
      - .env.local
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}

    networks:
      - connect
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

networks:
  connect:
    driver: bridge

volumes:
  webapp:
    driver: local
  log:
    driver: local
  vhosts:
    driver: local

  db-data:
    driver: local
