version: '3.9'

services:
  app:
    container_name: web-app
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    image: php:8.1-apache
    depends_on:
      - database
    networks:
      - appconnect
    ports:
      - "8000:80"
    volumes:
#      - .:/var/www/
      - app:/var/www/

  database:
    image: mysql:8.0
    container_name: db_app
    restart: always
    env_file:
      - .env
    environment:
#      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
#      MYSQL_DATABASE: ${MYSQL_DATABASE}
#      MYSQL_USER: ${MYSQL_USER}
#      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony-devops
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    networks:
      - appconnect
    ports:
    - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
#      - doctrine schema < sql

  jenkins:
    image: 'jenkins'
    container_name: "jenkins"
    labels:
      kompose.service.type: nodeport
    ports:
      - '8080:8080'
      - '443:8443'
      - '50000:50000'
    volumes:
      - /srv/data/jenkins_data:/jenkins_home
      - /srv/data/jenkins:/var/jenkins_config

#error services.networks must be a mapping
  networks:
    appconnect:
      driver: bridge

  volumes:
    db-data:
      driver: local
    jenkins_data:
      driver: local
    jenkins:
      driver: local




