<?php

namespace App\Entity;

use Faker;
use PHPUnit\Framework\TestCase;

class ProductTest extends TestCase
{
    private Product $product;
    private  $faker;



    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->product = new Product();
        $this->faker = Faker\Factory::create();
    }

    public function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }


    public function testSetName()
    {
        $expected = $this->faker->name();
        $this->product->setName($expected);
        $value = $this->product->getName();
        $this->assertContains($expected,$value);
    }


    public function testGetName()
    {
        $expected = $this->faker->name();
        $this->product->setName($expected);
        $value = $this->product->getName();
        // assertion

    }

    public function testSetCategory()
    {

    }

    public function testGetCategory()
    {

    }

    public function testSetDescription()
    {

    }

    public function testGetDescription()
    {

    }
}
