<?php

namespace App\Entity;

use App\Entity\Product;
use PHPUnit\Framework\TestCase;

class ProductTest extends TestCase
{
    private Product $product;

    public function setUp(): void
    {

        //product (instance)
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }


    public function testSetName()
    {
        $product = null;
        $product->setName('product name for test');

        // expected 'product name for test'
        // assertion
    }

    public function testSetStock()
    {

    }

    public function testGetPrice()
    {

    }

    public function testGetStock()
    {

    }

    public function testGetImages()
    {

    }

    public function testGetName()
    {

    }

    public function testSetCategory()
    {

    }

    public function testGetCategory()
    {

    }

    public function testGetDescription()
    {

    }

    public function testSetDescription()
    {

    }

    public function testSetPrice()
    {

    }


}
