apiVersion: v1

clusters:
  - cluster:
      certificate-authority-data: DATA+OMITTED
      server: https://8151BE598A0626585B9448CB12F8B9A4.gr7.us-east-1.eks.amazonaws.com
    name: arn:aws:eks:us-east-1:954141405434:cluster/test1

  - cluster:
      certificate-authority-data: DATA+OMITTED
      server: https://kubernetes.docker.internal:6443
    name: docker-desktop

  - cluster:
      certificate-authority-data: DATA+OMITTED
      server: https://8151BE598A0626585B9448CB12F8B9A4.gr7.us-east-1.eks.amazonaws.com
    name: test1.us-east-1.eksctl.io


contexts:
  - context:
      cluster: arn:aws:eks:us-east-1:954141405434:cluster/test1
      user: arn:aws:eks:us-east-1:954141405434:cluster/test1
    name: arn:aws:eks:us-east-1:954141405434:cluster/test1

  - context:
      cluster: docker-desktop
      user: docker-desktop
    name: docker-desktop

  - context:
      cluster: test1.us-east-1.eksctl.io
      user: iam-root-account@test1.us-east-1.eksctl.io
    name: iam-root-account@test1.us-east-1.eksctl.io

current-context: arn:aws:eks:us-east-1:954141405434:cluster/test1

kind: Config
preferences: {}

users:
  - name: arn:aws:eks:us-east-1:954141405434:cluster/test1
    user:
      exec:
        apiVersion: client.authentication.k8s.io/v1alpha1
        args:
          - --region
          - us-east-1
          - eks
          - get-token
          - --cluster-name
          - test1
        command: aws
        env: null
        interactiveMode: IfAvailable
        provideClusterInfo: false

  - name: docker-desktop
    user:
      client-certificate-data: REDACTED
      client-key-data: REDACTED

  - name: iam-root-account@test1.us-east-1.eksctl.io
    user:
      exec:
        apiVersion: client.authentication.k8s.io/v1beta1
        args:
          - eks
          - get-token
          - --output
          - json
          - --cluster-name
          - test1
          - --region
          - us-east-1
        command: aws
        env:
          - name: AWS_STS_REGIONAL_ENDPOINTS
            value: regional
        interactiveMode: IfAvailable
        provideClusterInfo: false